server:
  port: 8081
spring:
  config:
    import: "optional:file:.env[.properties],optional:file:../.env[.properties]"
  application:
    name: scraper-worker
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR}
  temporal:
    connection:
      target: ${TEMPORAL_HOST}:${TEMPORAL_PORT:7233}
    namespace: default
    workers-auto-discovery:
      packages:
        - com.checker

eh-config:
  cookies:
    member-id: ${EH_MEMBER_ID}
    pass-hash: ${EH_PASS_HASH}
    sk: ${EH_SK}
    star: ${EH_STAR}
  proxy:
    host: ${PROXY_HOST}
    port: ${PROXY_PORT:7893}
    username: ${PROXY_USERNAME}
    password: ${PROXY_PASSWORD}
    type: ${PROXY_TYPE:http}
