spring:
  application:
    name: temporal-eh-download
  datasource:
    url: jdbc:mysql://10.10.10.161:3306/eh_automation?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  temporal:
    connection:
      target: 10.10.10.161:7233
    namespace: default
    workers-auto-discovery:
      packages:
        - com.checker
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.checker.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
server:
  port: 8001

eh-config:
  # Cookie 信息
  cookies:
    member-id: "4674255"
    pass-hash: "0345da71457857378639a3a7f2eb045a"
    sk: "u2szd0pu6r7o3t3suf36iq1mr641"
    star: "1-2516af5cd7"
  # 代理信息
  proxy:
    host: "10.10.10.32"
    port: 7893
    username: "Clash"
    password: "azWPzWfP"
    type: "http"
  synology:
    url: "https://10.10.10.40:5001"
    username: "5465541"
    password: "Gcz@15271348205"
    destination: "n8n_bot/EHentai"
  notification:
    admin-email: "15272888596@163.com"
    tenant-id: a5f69b32-f12b-407f-b81e-a2b7057367dc
    client-id: ab36780f-0903-4fa2-9dfa-8a699fc4a2c4
    client-secret: g4W8Q~nzMeftYkOLJ3kiKPZkV1barzFIyMFyGc6a
    sender-email: ehbo@renl57.onmicrosoft.com
  komga:
    url: http://10.10.10.40:3001
    username: 15272888596@163.com
    password: 15271348205
    library-id: 0PWD8X2S9169Y
