server:
  port: 8082
spring:
  config:
    import: "optional:file:.env[.properties],optional:file:../.env[.properties]"
  application:
    name: eh-ai-service
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR}
  ai:
    openai:
      base-url: ${AI_BASE_URL}
      api-key: ${AI_API_KEY}
      chat:
        options:
          model: ${AI_MODEL}
