server:
  port: 8082
spring:
  config:
    import: "optional:file:.env[.properties],optional:file:../.env[.properties]"
  application:
    name: eh-ai-service
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR}
  ai:
    openai:
      base-url: ${AI_BASE_URL}
      api-key: ${AI_API_KEY}
      chat:
        options:
          model: ${AI_MODEL}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
  tracing:
    sampling:
      probability: ${TRACING_SAMPLE_RATE:0.0}
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://localhost:9411/api/v2/spans}
